### ISSUE TITLE
Fails to parse 

### ISSUE THREAD

**Issue by dudewad** [jdcataldo/grunt-groc#14]
When I use the example from the repo to run groc, it works fine. However, I use load-grunt-tasks to load my task configurations from a separate file and when I define it there, I get errors.

Here is the trace:

! Failed to parse doc tags C:\dev\server\wamp\www\testApp\app\scripts\app.js: Cannot read property '1' of null
   TypeError: Cannot read property '1' of null
    at Object.module.exports.DOC_TAGS.param.parseValue (C:\dev\server\wamp\www\testApp\node_modules\grunt-groc\node_modules\groc\lib\doc_tags.coffee:124:7)
    at Object.module.exports.Utils.parseDocTags (C:\dev\server\wamp\www\testApp\node_modules\grunt-groc\node_modules\groc\lib\utils.coffee:637:39)
    at Default.module.exports.Base.renderFile (C:\dev\server\wamp\www\testApp\node_modules\grunt-groc\node_modules\groc\lib\styles\base.coffee:27:11)
    at C:\dev\server\wamp\www\testApp\node_modules\grunt-groc\node_modules\groc\lib\project.coffee:83:15
    at fs.js:271:14
    at Object.oncomplete (fs.js:107:15)

Any idea what might cause this error? I know the configuration itself is valid because I can create multiple task types and it will try to run them with success. Running it with no files in the files array also runs successfully. I feel like it's just having issues reading the file or something?

Here is my task config:

module.exports = {
    javascript: {
        files: {src: ["<%=pkg.directories.dev_root %><%=pkg.directories.js %>*.js"]},
        options: {
            "out": "<%=pkg.directories.doc_root %>"
        }
    }
};

I'm running "groc:javascript", but as I said, if I define any other task name it finds and tries to run it.

**Comment by dudewad** [comment]
Retried on another project, don't get this issue. Not sure what the problem it but it's likely with the local grunt distro rather than grunt-groc. Will update if I find it to be an issue in the future.

**Comment by dudewad** [comment]
Okay, I figured out the issue:

This is not an issue with configuration, but rather an issue that I see as a Groc flaw. If a doc comment does not contain a data type along with the parameter descriptions, this error is thrown. For example, the following doc comment will cause the error above to be thrown:

    /**
     * Attaches all required listeners and does prep work for a drag of the scrubber
     * @param e Some event object
     */
    startDrag: function (e) {
        .....code.....
    }

Since "e" here is not assigned a data type, I get the ! Failed to parse.... error, with no details on where/why/what this error is.

This should be reduced to a WARNING severity level and continue on in my opinion. Or, at the very least, a descriptive error message should explain where the error occurred because right now "property 1 of null" inside some obscure loop in the Groc inner-workings is not troubleshootable. Though it looks to me like there's just no catch for a possible check against null, so try-catch might be the intended solution here, just not implemented yet. Hope this helps!

**Comment by jdcataldo** [comment]
Thanks for looking more into this. This doesn't look like an issue with the grunt plugin. Going to close this. You can file an issue against groc (https://github.com/nevir/groc).

**Comment by dudewad** [comment]
Will do, thanks!
